[package]
name = "aoc25-rust"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
hashbrown = "0.15.2"
radix_fmt = "1.0.0"
rayon = "1.10.0"
regex = "1.11.1"
